// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: master_sm.proto

package paxos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MasterOperator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodeid      uint64  `protobuf:"varint,1,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	Version     uint64  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Timeout     int32   `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Operator    uint32  `protobuf:"varint,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Sid         uint32  `protobuf:"varint,5,opt,name=sid,proto3" json:"sid,omitempty"`
	Lastversion *uint64 `protobuf:"varint,6,opt,name=lastversion,proto3,oneof" json:"lastversion,omitempty"`
}

func (x *MasterOperator) Reset() {
	*x = MasterOperator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_master_sm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterOperator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterOperator) ProtoMessage() {}

func (x *MasterOperator) ProtoReflect() protoreflect.Message {
	mi := &file_master_sm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterOperator.ProtoReflect.Descriptor instead.
func (*MasterOperator) Descriptor() ([]byte, []int) {
	return file_master_sm_proto_rawDescGZIP(), []int{0}
}

func (x *MasterOperator) GetNodeid() uint64 {
	if x != nil {
		return x.Nodeid
	}
	return 0
}

func (x *MasterOperator) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MasterOperator) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *MasterOperator) GetOperator() uint32 {
	if x != nil {
		return x.Operator
	}
	return 0
}

func (x *MasterOperator) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *MasterOperator) GetLastversion() uint64 {
	if x != nil && x.Lastversion != nil {
		return *x.Lastversion
	}
	return 0
}

var File_master_sm_proto protoreflect.FileDescriptor

var file_master_sm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x22, 0xc1, 0x01, 0x0a, 0x0e, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x6c, 0x65, 0x6e,
	0x53, 0x68, 0x61, 0x77, 0x31, 0x39, 0x2f, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x78,
	0x6f, 0x73, 0x3b, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_master_sm_proto_rawDescOnce sync.Once
	file_master_sm_proto_rawDescData = file_master_sm_proto_rawDesc
)

func file_master_sm_proto_rawDescGZIP() []byte {
	file_master_sm_proto_rawDescOnce.Do(func() {
		file_master_sm_proto_rawDescData = protoimpl.X.CompressGZIP(file_master_sm_proto_rawDescData)
	})
	return file_master_sm_proto_rawDescData
}

var file_master_sm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_master_sm_proto_goTypes = []interface{}{
	(*MasterOperator)(nil), // 0: paxos.MasterOperator
}
var file_master_sm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_master_sm_proto_init() }
func file_master_sm_proto_init() {
	if File_master_sm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_master_sm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterOperator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_master_sm_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_master_sm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_master_sm_proto_goTypes,
		DependencyIndexes: file_master_sm_proto_depIdxs,
		MessageInfos:      file_master_sm_proto_msgTypes,
	}.Build()
	File_master_sm_proto = out.File
	file_master_sm_proto_rawDesc = nil
	file_master_sm_proto_goTypes = nil
	file_master_sm_proto_depIdxs = nil
}
