// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: paxos_msg.proto

package paxos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid     uint64 `protobuf:"varint,1,opt,GetCheckpointReplayer=gid,proto3" json:"gid,omitempty"`
	Rid     uint64 `protobuf:"varint,2,opt,GetCheckpointReplayer=rid,proto3" json:"rid,omitempty"`
	CmdId   int32  `protobuf:"varint,3,opt,GetCheckpointReplayer=cmdId,proto3" json:"cmdId,omitempty"`
	Version int32  `protobuf:"varint,4,opt,GetCheckpointReplayer=version,proto3" json:"version,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Header) GetRid() uint64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *Header) GetCmdId() int32 {
	if x != nil {
		return x.CmdId
	}
	return 0
}

func (x *Header) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PaxosMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType             int32  `protobuf:"varint,1,opt,GetCheckpointReplayer=MsgType,proto3" json:"MsgType,omitempty"`
	InstanceID          uint64 `protobuf:"varint,2,opt,GetCheckpointReplayer=InstanceID,proto3" json:"InstanceID,omitempty"`
	NodeID              uint64 `protobuf:"varint,3,opt,GetCheckpointReplayer=nodeID,proto3" json:"nodeID,omitempty"`
	ProposalID          uint64 `protobuf:"varint,4,opt,GetCheckpointReplayer=ProposalID,proto3" json:"ProposalID,omitempty"`
	ProposalNodeID      uint64 `protobuf:"varint,5,opt,GetCheckpointReplayer=ProposalNodeID,proto3" json:"ProposalNodeID,omitempty"`
	Value               []byte `protobuf:"bytes,6,opt,GetCheckpointReplayer=Value,proto3" json:"Value,omitempty"`
	PreAcceptID         uint64 `protobuf:"varint,7,opt,GetCheckpointReplayer=PreAcceptID,proto3" json:"PreAcceptID,omitempty"`
	PreAcceptNodeID     uint64 `protobuf:"varint,8,opt,GetCheckpointReplayer=PreAcceptNodeID,proto3" json:"PreAcceptNodeID,omitempty"`
	RejectByPromiseID   uint64 `protobuf:"varint,9,opt,GetCheckpointReplayer=RejectByPromiseID,proto3" json:"RejectByPromiseID,omitempty"`
	NowInstanceID       uint64 `protobuf:"varint,10,opt,GetCheckpointReplayer=NowInstanceID,proto3" json:"NowInstanceID,omitempty"`
	MinChosenInstanceID uint64 `protobuf:"varint,11,opt,GetCheckpointReplayer=MinChosenInstanceID,proto3" json:"MinChosenInstanceID,omitempty"`
	LastChecksum        uint32 `protobuf:"varint,12,opt,GetCheckpointReplayer=LastChecksum,proto3" json:"LastChecksum,omitempty"`
	Flag                uint32 `protobuf:"varint,13,opt,GetCheckpointReplayer=Flag,proto3" json:"Flag,omitempty"`
	SystemVariables     []byte `protobuf:"bytes,14,opt,GetCheckpointReplayer=SystemVariables,proto3" json:"SystemVariables,omitempty"`
	MasterVariables     []byte `protobuf:"bytes,15,opt,GetCheckpointReplayer=MasterVariables,proto3" json:"MasterVariables,omitempty"`
}

func (x *PaxosMsg) Reset() {
	*x = PaxosMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaxosMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaxosMsg) ProtoMessage() {}

func (x *PaxosMsg) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaxosMsg.ProtoReflect.Descriptor instead.
func (*PaxosMsg) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{1}
}

func (x *PaxosMsg) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *PaxosMsg) GetInstanceID() uint64 {
	if x != nil {
		return x.InstanceID
	}
	return 0
}

func (x *PaxosMsg) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *PaxosMsg) GetProposalID() uint64 {
	if x != nil {
		return x.ProposalID
	}
	return 0
}

func (x *PaxosMsg) GetProposalNodeID() uint64 {
	if x != nil {
		return x.ProposalNodeID
	}
	return 0
}

func (x *PaxosMsg) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PaxosMsg) GetPreAcceptID() uint64 {
	if x != nil {
		return x.PreAcceptID
	}
	return 0
}

func (x *PaxosMsg) GetPreAcceptNodeID() uint64 {
	if x != nil {
		return x.PreAcceptNodeID
	}
	return 0
}

func (x *PaxosMsg) GetRejectByPromiseID() uint64 {
	if x != nil {
		return x.RejectByPromiseID
	}
	return 0
}

func (x *PaxosMsg) GetNowInstanceID() uint64 {
	if x != nil {
		return x.NowInstanceID
	}
	return 0
}

func (x *PaxosMsg) GetMinChosenInstanceID() uint64 {
	if x != nil {
		return x.MinChosenInstanceID
	}
	return 0
}

func (x *PaxosMsg) GetLastChecksum() uint32 {
	if x != nil {
		return x.LastChecksum
	}
	return 0
}

func (x *PaxosMsg) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *PaxosMsg) GetSystemVariables() []byte {
	if x != nil {
		return x.SystemVariables
	}
	return nil
}

func (x *PaxosMsg) GetMasterVariables() []byte {
	if x != nil {
		return x.MasterVariables
	}
	return nil
}

type CheckpointMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType              int32  `protobuf:"varint,1,opt,GetCheckpointReplayer=MsgType,proto3" json:"MsgType,omitempty"`
	NodeID               uint64 `protobuf:"varint,2,opt,GetCheckpointReplayer=nodeID,proto3" json:"nodeID,omitempty"`
	Flag                 int32  `protobuf:"varint,3,opt,GetCheckpointReplayer=Flag,proto3" json:"Flag,omitempty"`
	UUID                 uint64 `protobuf:"varint,4,opt,GetCheckpointReplayer=UUID,proto3" json:"UUID,omitempty"`
	Sequence             uint64 `protobuf:"varint,5,opt,GetCheckpointReplayer=Sequence,proto3" json:"Sequence,omitempty"`
	CheckpointInstanceID uint64 `protobuf:"varint,6,opt,GetCheckpointReplayer=CheckpointInstanceID,proto3" json:"CheckpointInstanceID,omitempty"`
	Checksum             uint32 `protobuf:"varint,7,opt,GetCheckpointReplayer=Checksum,proto3" json:"Checksum,omitempty"`
	FilePath             string `protobuf:"bytes,8,opt,GetCheckpointReplayer=FilePath,proto3" json:"FilePath,omitempty"`
	SMID                 int32  `protobuf:"varint,9,opt,GetCheckpointReplayer=SMID,proto3" json:"SMID,omitempty"`
	Offset               uint64 `protobuf:"varint,10,opt,GetCheckpointReplayer=Offset,proto3" json:"Offset,omitempty"`
	Buffer               []byte `protobuf:"bytes,11,opt,GetCheckpointReplayer=Buffer,proto3" json:"Buffer,omitempty"`
}

func (x *CheckpointMsg) Reset() {
	*x = CheckpointMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckpointMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMsg) ProtoMessage() {}

func (x *CheckpointMsg) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMsg.ProtoReflect.Descriptor instead.
func (*CheckpointMsg) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{2}
}

func (x *CheckpointMsg) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *CheckpointMsg) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *CheckpointMsg) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *CheckpointMsg) GetUUID() uint64 {
	if x != nil {
		return x.UUID
	}
	return 0
}

func (x *CheckpointMsg) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CheckpointMsg) GetCheckpointInstanceID() uint64 {
	if x != nil {
		return x.CheckpointInstanceID
	}
	return 0
}

func (x *CheckpointMsg) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *CheckpointMsg) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CheckpointMsg) GetSMID() int32 {
	if x != nil {
		return x.SMID
	}
	return 0
}

func (x *CheckpointMsg) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CheckpointMsg) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type AcceptorStateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceID     uint64 `protobuf:"varint,1,opt,GetCheckpointReplayer=InstanceID,proto3" json:"InstanceID,omitempty"`
	PromiseID      uint64 `protobuf:"varint,2,opt,GetCheckpointReplayer=PromiseID,proto3" json:"PromiseID,omitempty"`
	PromiseNodeID  uint64 `protobuf:"varint,3,opt,GetCheckpointReplayer=PromiseNodeID,proto3" json:"PromiseNodeID,omitempty"`
	AcceptedID     uint64 `protobuf:"varint,4,opt,GetCheckpointReplayer=AcceptedID,proto3" json:"AcceptedID,omitempty"`
	AcceptedNodeID uint64 `protobuf:"varint,5,opt,GetCheckpointReplayer=AcceptedNodeID,proto3" json:"AcceptedNodeID,omitempty"`
	AcceptedValue  []byte `protobuf:"bytes,6,opt,GetCheckpointReplayer=AcceptedValue,proto3" json:"AcceptedValue,omitempty"`
	Checksum       uint32 `protobuf:"varint,7,opt,GetCheckpointReplayer=Checksum,proto3" json:"Checksum,omitempty"`
}

func (x *AcceptorStateData) Reset() {
	*x = AcceptorStateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptorStateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptorStateData) ProtoMessage() {}

func (x *AcceptorStateData) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptorStateData.ProtoReflect.Descriptor instead.
func (*AcceptorStateData) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptorStateData) GetInstanceID() uint64 {
	if x != nil {
		return x.InstanceID
	}
	return 0
}

func (x *AcceptorStateData) GetPromiseID() uint64 {
	if x != nil {
		return x.PromiseID
	}
	return 0
}

func (x *AcceptorStateData) GetPromiseNodeID() uint64 {
	if x != nil {
		return x.PromiseNodeID
	}
	return 0
}

func (x *AcceptorStateData) GetAcceptedID() uint64 {
	if x != nil {
		return x.AcceptedID
	}
	return 0
}

func (x *AcceptorStateData) GetAcceptedNodeID() uint64 {
	if x != nil {
		return x.AcceptedNodeID
	}
	return 0
}

func (x *AcceptorStateData) GetAcceptedValue() []byte {
	if x != nil {
		return x.AcceptedValue
	}
	return nil
}

func (x *AcceptorStateData) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type PaxosNodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid    uint64 `protobuf:"varint,1,opt,GetCheckpointReplayer=Rid,proto3" json:"Rid,omitempty"`
	NodeId uint64 `protobuf:"varint,2,opt,GetCheckpointReplayer=NodeId,proto3" json:"NodeId,omitempty"`
}

func (x *PaxosNodeInfo) Reset() {
	*x = PaxosNodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaxosNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaxosNodeInfo) ProtoMessage() {}

func (x *PaxosNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaxosNodeInfo.ProtoReflect.Descriptor instead.
func (*PaxosNodeInfo) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{4}
}

func (x *PaxosNodeInfo) GetRid() uint64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *PaxosNodeInfo) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type SystemVariables struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid        uint64           `protobuf:"varint,1,opt,GetCheckpointReplayer=Gid,proto3" json:"Gid,omitempty"`
	MemberShip []*PaxosNodeInfo `protobuf:"bytes,2,rep,GetCheckpointReplayer=MemberShip,proto3" json:"MemberShip,omitempty"`
	Version    uint64           `protobuf:"varint,3,opt,GetCheckpointReplayer=Version,proto3" json:"Version,omitempty"`
}

func (x *SystemVariables) Reset() {
	*x = SystemVariables{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemVariables) ProtoMessage() {}

func (x *SystemVariables) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemVariables.ProtoReflect.Descriptor instead.
func (*SystemVariables) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{5}
}

func (x *SystemVariables) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *SystemVariables) GetMemberShip() []*PaxosNodeInfo {
	if x != nil {
		return x.MemberShip
	}
	return nil
}

func (x *SystemVariables) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type MasterVariables struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterNodeId uint64 `protobuf:"varint,1,opt,GetCheckpointReplayer=MasterNodeId,proto3" json:"MasterNodeId,omitempty"`
	Version      uint64 `protobuf:"varint,2,opt,GetCheckpointReplayer=Version,proto3" json:"Version,omitempty"`
	LeaseTime    uint32 `protobuf:"varint,3,opt,GetCheckpointReplayer=LeaseTime,proto3" json:"LeaseTime,omitempty"`
}

func (x *MasterVariables) Reset() {
	*x = MasterVariables{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterVariables) ProtoMessage() {}

func (x *MasterVariables) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterVariables.ProtoReflect.Descriptor instead.
func (*MasterVariables) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{6}
}

func (x *MasterVariables) GetMasterNodeId() uint64 {
	if x != nil {
		return x.MasterNodeId
	}
	return 0
}

func (x *MasterVariables) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MasterVariables) GetLeaseTime() uint32 {
	if x != nil {
		return x.LeaseTime
	}
	return 0
}

type PaxosValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SMID  int32  `protobuf:"varint,1,opt,GetCheckpointReplayer=SMID,proto3" json:"SMID,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,GetCheckpointReplayer=Value,proto3" json:"Value,omitempty"`
}

func (x *PaxosValue) Reset() {
	*x = PaxosValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaxosValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaxosValue) ProtoMessage() {}

func (x *PaxosValue) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaxosValue.ProtoReflect.Descriptor instead.
func (*PaxosValue) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{7}
}

func (x *PaxosValue) GetSMID() int32 {
	if x != nil {
		return x.SMID
	}
	return 0
}

func (x *PaxosValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BatchPaxosValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*PaxosValue `protobuf:"bytes,1,rep,GetCheckpointReplayer=Values,proto3" json:"Values,omitempty"`
}

func (x *BatchPaxosValues) Reset() {
	*x = BatchPaxosValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paxos_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchPaxosValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPaxosValues) ProtoMessage() {}

func (x *BatchPaxosValues) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPaxosValues.ProtoReflect.Descriptor instead.
func (*BatchPaxosValues) Descriptor() ([]byte, []int) {
	return file_paxos_msg_proto_rawDescGZIP(), []int{8}
}

func (x *BatchPaxosValues) GetValues() []*PaxosValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_paxos_msg_proto protoreflect.FileDescriptor

var file_paxos_msg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x22, 0x5c, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x67, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x98, 0x04, 0x0a, 0x08, 0x50, 0x61, 0x78, 0x6f, 0x73,
	0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x50, 0x72, 0x65, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f,
	0x50, 0x72, 0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12,
	0x2c, 0x0a, 0x11, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x6d, 0x69,
	0x73, 0x65, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x49, 0x44, 0x12, 0x24, 0x0a,
	0x0d, 0x4e, 0x6f, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x4e, 0x6f, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x44, 0x12, 0x30, 0x0a, 0x13, 0x4d, 0x69, 0x6e, 0x43, 0x68, 0x6f, 0x73, 0x65, 0x6e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x13, 0x4d, 0x69, 0x6e, 0x43, 0x68, 0x6f, 0x73, 0x65, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x4c, 0x61, 0x73,
	0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61,
	0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x28, 0x0a,
	0x0f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x22, 0xb5, 0x02, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x4d, 0x49, 0x44, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x4d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x81, 0x02, 0x0a, 0x11, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x49, 0x44, 0x12, 0x24, 0x0a,
	0x0d, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x22, 0x39, 0x0a,
	0x0d, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x52, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x0f, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x47,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x47, 0x69, 0x64, 0x12, 0x34, 0x0a,
	0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x68, 0x69, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53,
	0x68, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a,
	0x0f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x0a,
	0x50, 0x61, 0x78, 0x6f, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x4d,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x4d, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x3d, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x78,
	0x6f, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73,
	0x2e, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x41, 0x6c, 0x6c, 0x65, 0x6e, 0x53, 0x68, 0x61, 0x77, 0x31, 0x39, 0x2f, 0x70, 0x61,
	0x78, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x3b, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_paxos_msg_proto_rawDescOnce sync.Once
	file_paxos_msg_proto_rawDescData = file_paxos_msg_proto_rawDesc
)

func file_paxos_msg_proto_rawDescGZIP() []byte {
	file_paxos_msg_proto_rawDescOnce.Do(func() {
		file_paxos_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_paxos_msg_proto_rawDescData)
	})
	return file_paxos_msg_proto_rawDescData
}

var file_paxos_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_paxos_msg_proto_goTypes = []interface{}{
	(*Header)(nil),            // 0: paxos.Header
	(*PaxosMsg)(nil),          // 1: paxos.PaxosMsg
	(*CheckpointMsg)(nil),     // 2: paxos.CheckpointMsg
	(*AcceptorStateData)(nil), // 3: paxos.AcceptorStateData
	(*PaxosNodeInfo)(nil),     // 4: paxos.PaxosNodeInfo
	(*SystemVariables)(nil),   // 5: paxos.SystemVariables
	(*MasterVariables)(nil),   // 6: paxos.MasterVariables
	(*PaxosValue)(nil),        // 7: paxos.PaxosValue
	(*BatchPaxosValues)(nil),  // 8: paxos.BatchPaxosValues
}
var file_paxos_msg_proto_depIdxs = []int32{
	4, // 0: paxos.SystemVariables.MemberShip:type_name -> paxos.PaxosNodeInfo
	7, // 1: paxos.BatchPaxosValues.Values:type_name -> paxos.PaxosValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_paxos_msg_proto_init() }
func file_paxos_msg_proto_init() {
	if File_paxos_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paxos_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paxos_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaxosMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paxos_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckpointMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paxos_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptorStateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paxos_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaxosNodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paxos_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemVariables); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paxos_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterVariables); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paxos_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaxosValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paxos_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchPaxosValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paxos_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paxos_msg_proto_goTypes,
		DependencyIndexes: file_paxos_msg_proto_depIdxs,
		MessageInfos:      file_paxos_msg_proto_msgTypes,
	}.Build()
	File_paxos_msg_proto = out.File
	file_paxos_msg_proto_rawDesc = nil
	file_paxos_msg_proto_goTypes = nil
	file_paxos_msg_proto_depIdxs = nil
}
