// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: paxoskv.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaxosKVServerClient is the client API for PaxosKVServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaxosKVServerClient interface {
	Put(ctx context.Context, in *KVOperator, opts ...grpc.CallOption) (*KVResponse, error)
	GetLocal(ctx context.Context, in *KVOperator, opts ...grpc.CallOption) (*KVResponse, error)
	GetGlobal(ctx context.Context, in *KVOperator, opts ...grpc.CallOption) (*KVResponse, error)
	Delete(ctx context.Context, in *KVOperator, opts ...grpc.CallOption) (*KVResponse, error)
}

type paxosKVServerClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosKVServerClient(cc grpc.ClientConnInterface) PaxosKVServerClient {
	return &paxosKVServerClient{cc}
}

func (c *paxosKVServerClient) Put(ctx context.Context, in *KVOperator, opts ...grpc.CallOption) (*KVResponse, error) {
	out := new(KVResponse)
	err := c.cc.Invoke(ctx, "/paxoskv.PaxosKVServer/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosKVServerClient) GetLocal(ctx context.Context, in *KVOperator, opts ...grpc.CallOption) (*KVResponse, error) {
	out := new(KVResponse)
	err := c.cc.Invoke(ctx, "/paxoskv.PaxosKVServer/GetLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosKVServerClient) GetGlobal(ctx context.Context, in *KVOperator, opts ...grpc.CallOption) (*KVResponse, error) {
	out := new(KVResponse)
	err := c.cc.Invoke(ctx, "/paxoskv.PaxosKVServer/GetGlobal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosKVServerClient) Delete(ctx context.Context, in *KVOperator, opts ...grpc.CallOption) (*KVResponse, error) {
	out := new(KVResponse)
	err := c.cc.Invoke(ctx, "/paxoskv.PaxosKVServer/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosKVServerServer is the server API for PaxosKVServer service.
// All implementations must embed UnimplementedPaxosKVServerServer
// for forward compatibility
type PaxosKVServerServer interface {
	Put(context.Context, *KVOperator) (*KVResponse, error)
	GetLocal(context.Context, *KVOperator) (*KVResponse, error)
	GetGlobal(context.Context, *KVOperator) (*KVResponse, error)
	Delete(context.Context, *KVOperator) (*KVResponse, error)
	mustEmbedUnimplementedPaxosKVServerServer()
}

// UnimplementedPaxosKVServerServer must be embedded to have forward compatible implementations.
type UnimplementedPaxosKVServerServer struct {
}

func (UnimplementedPaxosKVServerServer) Put(context.Context, *KVOperator) (*KVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedPaxosKVServerServer) GetLocal(context.Context, *KVOperator) (*KVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocal not implemented")
}
func (UnimplementedPaxosKVServerServer) GetGlobal(context.Context, *KVOperator) (*KVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobal not implemented")
}
func (UnimplementedPaxosKVServerServer) Delete(context.Context, *KVOperator) (*KVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPaxosKVServerServer) mustEmbedUnimplementedPaxosKVServerServer() {}

// UnsafePaxosKVServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosKVServerServer will
// result in compilation errors.
type UnsafePaxosKVServerServer interface {
	mustEmbedUnimplementedPaxosKVServerServer()
}

func RegisterPaxosKVServerServer(s grpc.ServiceRegistrar, srv PaxosKVServerServer) {
	s.RegisterService(&PaxosKVServer_ServiceDesc, srv)
}

func _PaxosKVServer_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVOperator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosKVServerServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxoskv.PaxosKVServer/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosKVServerServer).Put(ctx, req.(*KVOperator))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosKVServer_GetLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVOperator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosKVServerServer).GetLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxoskv.PaxosKVServer/GetLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosKVServerServer).GetLocal(ctx, req.(*KVOperator))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosKVServer_GetGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVOperator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosKVServerServer).GetGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxoskv.PaxosKVServer/GetGlobal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosKVServerServer).GetGlobal(ctx, req.(*KVOperator))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosKVServer_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVOperator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosKVServerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxoskv.PaxosKVServer/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosKVServerServer).Delete(ctx, req.(*KVOperator))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosKVServer_ServiceDesc is the grpc.ServiceDesc for PaxosKVServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosKVServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxoskv.PaxosKVServer",
	HandlerType: (*PaxosKVServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _PaxosKVServer_Put_Handler,
		},
		{
			MethodName: "GetLocal",
			Handler:    _PaxosKVServer_GetLocal_Handler,
		},
		{
			MethodName: "GetGlobal",
			Handler:    _PaxosKVServer_GetGlobal_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PaxosKVServer_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxoskv.proto",
}
